### PR TITLE
fix(display): don't run both root and regular actions on failure

### LINKED ISSUE #49: `run` assumes that root actions terminate
See https://github.com/atalii/ttds/pull/35#issuecomment-2698734706.

When a nonterminating root action is run, there's not an unambiguous indicator that `call_action` succeeded with a root action, so it tries to call regular actions afterward (and fails).

https://github.com/atalii/ttds/blob/a23850d7b135d4a3aa249b3ae66e89306a53e39d/display/threads/commands.c#L269-L281

### PR DESCRIPTION
**Pull request by ulahello**
It works in practice (until the [test backend](#35) is merged) because the sole root action also terminates, so the doubling never occurs.

Fixes #49.

### CODE REVIEW

**Comment by atalii** [comment]
Having a boolean output ptr is a much better shape, ty!!

File: display/threads/commands.c [hunk 1]
```diff
@@ -258,25 +260,27 @@ static char *call_action(struct ui_ctx *ctx, const struct command *c,
...
+
+	char *ret = malloc(512);
+	snprintf(ret, 512, "no such action found: %s", c->action);
+	return ret;
 }
 
 static char *run(struct ui_ctx *ctx, const struct command *c)
 {
 	char *ret = NULL;
+	bool found;
```
Comment (atalii) [inline display/threads/commands.c:273]: Need this be initialized?

Comment (atalii) [reply display/threads/commands.c:273]: (ig not unless root actions is empty? may as well set it to false on init?)

Comment (ulahello) [reply display/threads/commands.c:273]: Oh whoops I didn't see this- it's unconditionally initialized by `call_action` and `run` only reads it after calling `call_action`.
